--- 
abstract: mod_perl2 handler for Mojo
author: 
  - Uwe Voelker <uwe.voelker@gmx.de>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: Apache2-Mojo
requires: 
  Apache2: 0
  Mojo: 0
version: 0.001
